spring:
  datasource:
    url: jdbc:h2:mem:notificationdb
    driver-class-name: org.h2.Driver
    username: ${db.username:username}
    password: ${db.password:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  cloud:
    stream:
      default-binder: rabbit
      bindings:
        notification-in-0:
          destination: orders
          group: notification-group
          content-type: application/json
          consumer:
            auto-startup: true
            
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${rabbitmq.username:guest}
    password: ${rabbitmq.password:guest}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - bus-refresh
          - prometheus
          
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}      
      
  prometheus:
    metrics:
      export:
        enabled: true
       
custom:
  message: "Welcome to the Notification Service!"


