spring:
  datasource:
    url: jdbc:h2:mem:notificationdb
    driver-class-name: org.h2.Driver
    username: ${db.username:sa}
    password: ${db.password:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

custom:
  message: "Welcome to the Notification Service!"
