spring:
  datasource:
    url: jdbc:h2:mem:notificationdb
    driver-class-name: org.h2.Driver
    username: ${db.username:username}
    password: ${db.password:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  cloud:
    function:
      definition: notification
    stream:
      bindings:
        notification-in-0:
          destination: orders

custom:
  message: "Welcome to the Notification Service!"
