spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: ${db.username:username}
    password: ${db.password:password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

    stream:
      default-binder: rabbit
      bindings:
        order-out-0:                # producer -> publish events
          destination: orders
          content-type: application/json
          producer:
            autoStartup: true       # asigură pornirea bindingului
      rabbit:
        bindings:
          order-out-0:
            producer:
              declareExchange: true # creează exchange-ul dacă nu există

resilience4j:
  circuitbreaker:
    instances:
      product-service:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

custom:
  message: "Welcome to the Order Service!"
