spring:
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: ${db.username:username}
    password: ${db.password:password}

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console:
      enabled: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      
custom:
  message: "Welcome to the Product Service!"
